Update ci-cd.yml

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -1,53 +1,53 @@
-name: Build Docker Image and Trivy Scan
+# name: Build Docker Image and Trivy Scan
 
-on:
-  push:
-    branches:
-      - main
+# on:
+#   push:
+#     branches:
+#       - main
 
-jobs:
-  build-and-scan:
-    runs-on: ubuntu-latest
+# jobs:
+#   build-and-scan:
+#     runs-on: ubuntu-latest
 
-    steps:
-    - name: Checkout code
-      uses: actions/checkout@v2
+#     steps:
+#     - name: Checkout code
+#       uses: actions/checkout@v2
 
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+#     - name: Log in to Docker Hub
+#       uses: docker/login-action@v2
+#       with:
+#         username: ${{ secrets.DOCKER_USERNAME }}
+#         password: ${{ secrets.DOCKER_PASSWORD }}
 
-    - name: Build Docker Image
-      run: |
-        docker build -t amanvermaclouddrove/react:latest .
+#     - name: Build Docker Image
+#       run: |
+#         docker build -t amanvermaclouddrove/react:latest .
 
-    - name: Install Trivy
-      run: |
-        wget https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb
-        sudo dpkg -i trivy_0.34.0_Linux-64bit.deb
+#     - name: Install Trivy
+#       run: |
+#         wget https://github.com/aquasecurity/trivy/releases/download/v0.34.0/trivy_0.34.0_Linux-64bit.deb
+#         sudo dpkg -i trivy_0.34.0_Linux-64bit.deb
 
-    - name: Run Trivy Scan on Docker Image
-      run: trivy image --exit-code 0 --format json --output ./vulnerabilities.json amanvermaclouddrove/react:latest
+#     - name: Run Trivy Scan on Docker Image
+#       run: trivy image --exit-code 0 --format json --output ./vulnerabilities.json amanvermaclouddrove/react:latest
 
-    - name: Check for Critical and High Vulnerabilities
-      id: check_vulnerabilities
-      run: |
-        jq '.Results[].Vulnerabilities[] | select(.Severity == "CRITICAL" or .Severity == "HIGH")' vulnerabilities.json > critical_and_high_vulnerabilities.json
-        if [ -s critical_and_high_vulnerabilities.json ]; then
-          echo "found=true" >> $GITHUB_ENV
-        else
-          echo "found=false" >> $GITHUB_ENV
-        fi
+#     - name: Check for Critical and High Vulnerabilities
+#       id: check_vulnerabilities
+#       run: |
+#         jq '.Results[].Vulnerabilities[] | select(.Severity == "CRITICAL" or .Severity == "HIGH")' vulnerabilities.json > critical_and_high_vulnerabilities.json
+#         if [ -s critical_and_high_vulnerabilities.json ]; then
+#           echo "found=true" >> $GITHUB_ENV
+#         else
+#           echo "found=false" >> $GITHUB_ENV
+#         fi
 
-    - name: Fail if Critical or High Vulnerabilities Found
-      if: env.found == 'true'
-      run: |
-        echo "Critical or high vulnerabilities found:"
-        cat critical_and_high_vulnerabilities.json
-        exit 1
+#     - name: Fail if Critical or High Vulnerabilities Found
+#       if: env.found == 'true'
+#       run: |
+#         echo "Critical or high vulnerabilities found:"
+#         cat critical_and_high_vulnerabilities.json
+#         exit 1
 
-    - name: Push Docker Image to Docker Hub
-      if: env.found == 'false'
-      run: docker push amanvermaclouddrove/react:latest
+#     - name: Push Docker Image to Docker Hub
+#       if: env.found == 'false'
+#       run: docker push amanvermaclouddrove/react:latest
